hibernate.connection.driver_class = your_driver
hibernate.connection.url = your_database_url
hibernate.connection.username = username
hibernate.connection.password = password
hibernate.dialect = org.hibernate.dialect.MySQLDialect