package connection;

public enum RequestType {
    REGISTER,
    LOGIN,
    DISCONNECT,

    GET_ALL_USERS,
    MODIFY_USER,
    REMOVE_USER,
    GET_UNREGISTERED_PARTNER_USERS,

    GET_ALL_SUPPLIERS,
    ADD_SUPPLIER,
    MODIFY_SUPPLIER,
    REMOVE_SUPPLIER,

    GET_ALL_PRODUCTS,
    ADD_PRODUCT,
    MODIFY_PRODUCT,
    REMOVE_PRODUCT,
    GET_UNUSED_PRODUCTS,
    GET_UNORDERED_PRODUCTS,

    GET_ALL_REQUESTS,
    ADD_REQUEST,
    MODIFY_REQUEST,
    REMOVE_REQUEST,
    GET_OWN_REQUESTS,

    GET_ASSOCIATED_REQUESTPRODUCTS,

    GET_ALL_ORDERS,
    ADD_ORDER,
    MODIFY_ORDER,
    REMOVE_ORDER,
    GET_OWN_ORDERS,
    GET_ASSOCIATED_ORDERS,

    GET_ASSOCIATED_ORDERPRODUCTS
}
